### ISSUE TITLE
Local build fails

### ISSUE THREAD

**Issue by dejanu** [alexmacavei/events-application#21]
## Issue

* While following readme.md and building the app locally: `npx nx affected -t build` also `npx nx list` fails

```bash
/home/dej/.npm/_npx/3294051/lib/node_modules/nx/src/project-graph/nx-deps-cache.js:51
    return data ?? null;
                 ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/dej/.npm/_npx/3294051/lib/node_modules/nx/src/project-graph/project-graph.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nx@17.2.8 postinstall: `node ./bin/post-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nx@17.2.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

* npm version npm@6.14.4
* npx 6.14.4

**Comment by alexmacavei** [comment]
Is this still a thing?
